name: Test_homework (Run Tests)

on:
  pull_request:
    branches:
      - homework8

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Setup dependencies
        run: npm install

      - name: Run password-checker tests
        run: npm test
        with:
          args: '--testPathPattern="password-checker"'